name: rihla
description: "Application mobile touristique Rihla."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  flutter_compass: ^0.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http: ^1.2.2
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.5.6
  sqflite: ^2.3.3
  path: ^1.9.0
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
